// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Agent = __t.object("Agent", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  registeredAt: __t.timestamp(),
});
export type Agent = __Infer<typeof Agent>;

export const Entity = __t.object("Entity", {
  id: __t.u64(),
  name: __t.string(),
  kind: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Entity = __Infer<typeof Entity>;

export const MemoryNote = __t.object("MemoryNote", {
  id: __t.u64(),
  content: __t.string(),
  addedBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type MemoryNote = __Infer<typeof MemoryNote>;

export const NoteEntity = __t.object("NoteEntity", {
  id: __t.u64(),
  noteId: __t.u64(),
  entityId: __t.u64(),
});
export type NoteEntity = __Infer<typeof NoteEntity>;

