import { writeFileSync, mkdirSync, existsSync, readFileSync, appendFileSync } from 'fs';
import { join } from 'path';
import chalk from 'chalk';
import type { InitAnswers } from './prompts.js';
import type { ProvisionResult } from './provision_db.js';

const MARKER_DIR = '.spacetimedb-memory-mmo';

export function writeEnv(answers: InitAnswers, prov: ProvisionResult): { dir: string; envPath: string } {
  const projectRoot = process.cwd();
  const dir = join(projectRoot, MARKER_DIR);
  mkdirSync(dir, { recursive: true });

  const envPath = join(dir, '.env');
  const envBody = [
    `# Auto-generated by spacetimedb-memory-mmo init`,
    `SPACETIMEDB_HOST=${prov.host}`,
    `SPACETIMEDB_DB_NAME=${prov.databaseName}`,
    answers.anthropicApiKey ? `ANTHROPIC_API_KEY=${answers.anthropicApiKey}` : `# ANTHROPIC_API_KEY=`,
    answers.voyageApiKey ? `VOYAGE_API_KEY=${answers.voyageApiKey}` : `# VOYAGE_API_KEY=`,
    `VOYAGE_EMBEDDING_MODEL=${answers.voyageEmbeddingModel}`,
    ``,
  ].join('\n');
  writeFileSync(envPath, envBody, { mode: 0o600 });

  const configPath = join(dir, 'config.json');
  const config = {
    version: 1,
    initializedAt: new Date().toISOString(),
    backend: answers.backend,
    databaseName: prov.databaseName,
    host: prov.host,
    hosts: answers.hosts,
  };
  writeFileSync(configPath, JSON.stringify(config, null, 2));

  const readmePath = join(dir, 'README.md');
  writeFileSync(
    readmePath,
    [
      `# .spacetimedb-memory-mmo/`,
      ``,
      `This directory was created by \`npx spacetimedb-memory-mmo init\`.`,
      ``,
      `- \`.env\` — secrets and connection config (DO NOT COMMIT)`,
      `- \`config.json\` — non-secret record of choices made`,
      ``,
      `Re-run setup: \`npx spacetimedb-memory-mmo init\`.`,
      `Diagnose:    \`npx spacetimedb-memory-mmo doctor\`.`,
      `Remove:      \`npx spacetimedb-memory-mmo reset\`.`,
      ``,
    ].join('\n')
  );

  // Update .gitignore in project root (idempotent)
  const gitignorePath = join(projectRoot, '.gitignore');
  const ignoreLine = `${MARKER_DIR}/`;
  if (existsSync(gitignorePath)) {
    const current = readFileSync(gitignorePath, 'utf8');
    if (!current.split(/\r?\n/).includes(ignoreLine)) {
      appendFileSync(gitignorePath, `\n# Added by spacetimedb-memory-mmo\n${ignoreLine}\n`);
      console.log(chalk.green(`✓ Added ${ignoreLine} to .gitignore`));
    }
  } else {
    writeFileSync(gitignorePath, `# Created by spacetimedb-memory-mmo\n${ignoreLine}\n`);
    console.log(chalk.green(`✓ Created .gitignore with ${ignoreLine}`));
  }

  console.log(chalk.green(`✓ Wrote ${envPath}`));
  return { dir, envPath };
}
