// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddMemoryReducer from "../add_memory_reducer";
import AddMemoryWithEntitiesReducer from "../add_memory_with_entities_reducer";
import DeleteMemoryReducer from "../delete_memory_reducer";
import SetAgentNameReducer from "../set_agent_name_reducer";

export type AddMemoryParams = __Infer<typeof AddMemoryReducer>;
export type AddMemoryWithEntitiesParams = __Infer<typeof AddMemoryWithEntitiesReducer>;
export type DeleteMemoryParams = __Infer<typeof DeleteMemoryReducer>;
export type SetAgentNameParams = __Infer<typeof SetAgentNameReducer>;

